### ISSUE TITLE
Any discord user can PM commands to the bot.

### ISSUE THREAD

**Issue by maxwenger** [maxwenger/MeerChat#18]
- [ ] Require the user to be registered with the plugin to use commands in discord
- [ ] Only allow commands that the player would normally be able to proform

**Comment by maxwenger** [comment]
How do you feel about using the command `/meerchat register <Username#0000>` to link a Minecraft account to a discord account?

How could you see this being abused @metherul?

I was also planning on using just a csv to save the data.

**Comment by metherul** [comment]
Lemme start working on the DB and Minecraft chat interfaces. Shouldn't be too hard!

**Comment by maxwenger** [comment]
Just made it so all messages to the bot are received as a message, this is more useful functionality, for now, and solves our security problem.
